export const countryNames = {
 "ad": "Andorra",
 "ae": "United Arab Emirates",
 "af": "Afghanistan",
 "ag": "Antigua and Barbuda",
 "ai": "Anguilla",
 "al": "Albania",
 "am": "Armenia",
 "ao": "Angola",
 "aq": "Antarctica",
 "ar": "Argentina",
 "as": "American Samoa",
 "at": "Austria",
 "au": "Australia",
 "aw": "Aruba",
 "ax": "Åland Islands",
 "az": "Azerbaijan",
 "ba": "Bosnia and Herzegovina",
 "bb": "Barbados",
 "bd": "Bangladesh",
 "be": "Belgium",
 "bf": "Burkina Faso",
 "bg": "Bulgaria",
 "bh": "Bahrain",
 "bi": "Burundi",
 "bj": "Benin",
 "bl": "Saint Barthélemy",
 "bm": "Bermuda",
 "bn": "Brunei Darussalam",
 "bo": "Bolivia, Plurinational State of",
 "bq": "Bonaire, Sint Eustatius and Saba",
 "br": "Brazil",
 "bs": "Bahamas",
 "bt": "Bhutan",
 "bv": "Bouvet Island",
 "bw": "Botswana",
 "by": "Belarus",
 "bz": "Belize",
 "ca": "Canada",
 "cc": "Cocos (Keeling) Islands",
 "cd": "Congo, Democratic Republic of the",
 "cf": "Central African Republic",
 "cg": "Congo",
 "ch": "Switzerland",
 "ci": "Côte d'Ivoire",
 "ck": "Cook Islands",
 "cl": "Chile",
 "cm": "Cameroon",
 "cn": "China",
 "co": "Colombia",
 "cr": "Costa Rica",
 "cu": "Cuba",
 "cv": "Cabo Verde",
 "cw": "Curaçao",
 "cx": "Christmas Island",
 "cy": "Cyprus",
 "cz": "Czechia",
 "de": "Germany",
 "dj": "Djibouti",
 "dk": "Denmark",
 "dm": "Dominica",
 "do": "Dominican Republic",
 "dz": "Algeria",
 "ec": "Ecuador",
 "ee": "Estonia",
 "eg": "Egypt",
 "eh": "Western Sahara",
 "er": "Eritrea",
 "es": "Spain",
 "et": "Ethiopia",
 "fi": "Finland",
 "fj": "Fiji",
 "fk": "Falkland Islands (Malvinas)",
 "fm": "Micronesia, Federated States of",
 "fo": "Faroe Islands",
 "fr": "France",
 "ga": "Gabon",
 "gb": "United Kingdom of Great Britain and Northern Ireland",
 "gd": "Grenada",
 "ge": "Georgia",
 "gf": "French Guiana",
 "gg": "Guernsey",
 "gh": "Ghana",
 "gi": "Gibraltar",
 "gl": "Greenland",
 "gm": "Gambia",
 "gn": "Guinea",
 "gp": "Guadeloupe",
 "gq": "Equatorial Guinea",
 "gr": "Greece",
 "gs": "South Georgia and the South Sandwich Islands",
 "gt": "Guatemala",
 "gu": "Guam",
 "gw": "Guinea-Bissau",
 "gy": "Guyana",
 "hk": "Hong Kong",
 "hm": "Heard Island and McDonald Islands",
 "hn": "Honduras",
 "hr": "Croatia",
 "ht": "Haiti",
 "hu": "Hungary",
 "id": "Indonesia",
 "ie": "Ireland",
 "il": "Israel",
 "im": "Isle of Man",
 "in": "India",
 "io": "British Indian Ocean Territory",
 "iq": "Iraq",
 "ir": "Iran, Islamic Republic of",
 "is": "Iceland",
 "it": "Italy",
 "je": "Jersey",
 "jm": "Jamaica",
 "jo": "Jordan",
 "jp": "Japan",
 "ke": "Kenya",
 "kg": "Kyrgyzstan",
 "kh": "Cambodia",
 "ki": "Kiribati",
 "km": "Comoros",
 "kn": "Saint Kitts and Nevis",
 "kp": "Korea, Democratic People's Republic of",
 "kr": "Korea, Republic of",
 "kw": "Kuwait",
 "ky": "Cayman Islands",
 "kz": "Kazakhstan",
 "la": "Lao People's Democratic Republic",
 "lb": "Lebanon",
 "lc": "Saint Lucia",
 "li": "Liechtenstein",
 "lk": "Sri Lanka",
 "lr": "Liberia",
 "ls": "Lesotho",
 "lt": "Lithuania",
 "lu": "Luxembourg",
 "lv": "Latvia",
 "ly": "Libya",
 "ma": "Morocco",
 "mc": "Monaco",
 "md": "Moldova, Republic of",
 "me": "Montenegro",
 "mf": "Saint Martin (French part)",
 "mg": "Madagascar",
 "mh": "Marshall Islands",
 "mk": "North Macedonia",
 "ml": "Mali",
 "mm": "Myanmar",
 "mn": "Mongolia",
 "mo": "Macao",
 "mp": "Northern Mariana Islands",
 "mq": "Martinique",
 "mr": "Mauritania",
 "ms": "Montserrat",
 "mt": "Malta",
 "mu": "Mauritius",
 "mv": "Maldives",
 "mw": "Malawi",
 "mx": "Mexico",
 "my": "Malaysia",
 "mz": "Mozambique",
 "na": "Namibia",
 "nc": "New Caledonia",
 "ne": "Niger",
 "nf": "Norfolk Island",
 "ng": "Nigeria",
 "ni": "Nicaragua",
 "nl": "Netherlands, Kingdom of the",
 "no": "Norway",
 "np": "Nepal",
 "nr": "Nauru",
 "nu": "Niue",
 "nz": "New Zealand",
 "om": "Oman",
 "pa": "Panama",
 "pe": "Peru",
 "pf": "French Polynesia",
 "pg": "Papua New Guinea",
 "ph": "Philippines",
 "pk": "Pakistan",
 "pl": "Poland",
 "pm": "Saint Pierre and Miquelon",
 "pn": "Pitcairn",
 "pr": "Puerto Rico",
 "ps": "Palestine, State of",
 "pt": "Portugal",
 "pw": "Palau",
 "py": "Paraguay",
 "qa": "Qatar",
 "re": "Réunion",
 "ro": "Romania",
 "rs": "Serbia",
 "ru": "Russian Federation",
 "rw": "Rwanda",
 "sa": "Saudi Arabia",
 "sb": "Solomon Islands",
 "sc": "Seychelles",
 "sd": "Sudan",
 "se": "Sweden",
 "sg": "Singapore",
 "sh": "Saint Helena, Ascension and Tristan da Cunha",
 "si": "Slovenia",
 "sj": "Svalbard and Jan Mayen",
 "sk": "Slovakia",
 "sl": "Sierra Leone",
 "sm": "San Marino",
 "sn": "Senegal",
 "so": "Somalia",
 "sr": "Suriname",
 "ss": "South Sudan",
 "st": "Sao Tome and Principe",
 "sv": "El Salvador",
 "sx": "Sint Maarten (Dutch part)",
 "sy": "Syrian Arab Republic",
 "sz": "Eswatini",
 "tc": "Turks and Caicos Islands",
 "td": "Chad",
 "tf": "French Southern Territories",
 "tg": "Togo",
 "th": "Thailand",
 "tj": "Tajikistan",
 "tk": "Tokelau",
 "tl": "Timor-Leste",
 "tm": "Turkmenistan",
 "tn": "Tunisia",
 "to": "Tonga",
 "tr": "Türkiye",
 "tt": "Trinidad and Tobago",
 "tv": "Tuvalu",
 "tw": "Taiwan, Province of China",
 "tz": "Tanzania, United Republic of",
 "ua": "Ukraine",
 "ug": "Uganda",
 "um": "United States Minor Outlying Islands",
 "us": "United States of America",
 "uy": "Uruguay",
 "uz": "Uzbekistan",
 "va": "Holy See",
 "vc": "Saint Vincent and the Grenadines",
 "ve": "Venezuela, Bolivarian Republic of",
 "vg": "Virgin Islands (British)",
 "vi": "Virgin Islands (U.S.)",
 "vn": "Viet Nam",
 "vu": "Vanuatu",
 "wf": "Wallis and Futuna",
 "ws": "Samoa",
 "ye": "Yemen",
 "yt": "Mayotte",
 "za": "South Africa",
 "zm": "Zambia",
 "zw": "Zimbabwe"
}

export const secondLevels = {
	"at": ["ac", "gv", "co", "or", "priv" ],

	"au": ["com", "net", "org", "edu", "gov", "asn", "id", "csiro"],

	"br": [ "9guacu", "abc", "adm", "adv", "agr", "aju", "am", "anani", "aparecida", "app", "arq", "art", "ato", 
	  "b", "barueri", "belem", "bhz", "bib", "bio", "blog", "bmd", "boavista", "bsb", "campinagrande", "campinas",
	  "caxias", "cim", "cng", "cnt", "com", "contagem", "coop", "coz", "cuiaba", "curitiba", "def", "des", "det",
	  "dev", "ecn", "eco", "edu", "emp", "enf", "eng", "esp", "etc", "eti", "far", "feira", "flog", "floripa", 
	  "fm", "fnd", "fortal", "fot", "foz", "fst", "geo", "ggf", "goiania", "gov", "gru", "imb", "ind", "inf", 
	  "jab", "jampa", "jdf", "joinville", "jor", "jus", "leg", "lel", "log", "londrina", "macapa", "maceio", 
	  "manaus", "maringa", "mat", "med", "mil", "morena", "mp", "mus", "natal", "net", "niteroi", "nom", "not",
	  "ntr", "odo", "ong", "org", "osasco", "palmas", "poa", "ppg", "pro", "psc", "psi", "pvh", "qsl", "radio",
	  "rec", "recife", "rep", "ribeirao", "rio", "riobranco", "riopreto", "salvador", "sampa", "santamaria",
	  "santoandre", "saobernardo", "saogonca", "seg", "sjc", "slg", "slz", "sorocaba", "srv", "taxi", "tc",
	  "tec", "teo", "the", "tmp", "trd", "tur", "tv", "udi", "vet", "vix", "vlog", "wiki", "zlg" ],

	"dz": [ "com", "gov", "org", "edu", "asso", "pol", "art", "net", "tm", "soc" ],

	"es": [ "com","nom","org","gob","edu" ],

	"fr": [ "aeroport","avoues","cci","chambagri","chirurgiens-dentistes","experts-comptables","geometre-expert",
		"greta","huissier-justice","medecin","notaires","pharmacien","port","veterinaire","prd" ],

	"hu": [ "2000","agrar","bolt","city","co","casino","edu","film","forum","games","gov","hotel","info","ingatlan",
		"jogasz","konyvelo","erotica","erotika","sex","szex","lakas","media","mobi","net","news","org","priv","reklam",
		"shop","sport","suli","tm","tozsde","utazas","video" ],

	"il": [ "ac","co","org","net","k12","gov","muni","idf" ],

	"in": [ "co","com","firm","net","org","gen","ind","ernet","ac","edu","res","gov","mil","5g","6g","ai","am","bihar",
		"biz","business","ca","cn","com","coop","cs","delhi","dr","er","gujarat","info","int","internet","io","me","pg",
		"post","pro","travel","tv","uk","up","us" ],

	"jp": [ "ac","ad","co","ed","go","gr","lg","ne","or" ],

	"kr": [ "co","ne","or","re","pe","go","mil","ac","hs","ms","es","sc","kg","seoul","busan","daegu","incheon",
		"gwangju","daejeon","ulsan","gyeonggi","gangwon","chungbuk","chungnam","jeonbuk","jeonnam","gyeongbuk",
		"gyeongnam","jeju" ],

	"lk": [ "gov","ac","sch","net","int","com","org","edu","ngo","soc","web","ltd","assn","grp","hotel" ],

	"nz": [ "ac","co","geek","gen","kiwi","maori","net","org","school","cri","govt","health","iwi","mil","parliament" ],

	"pk": [ "com","org","net","edu","res","gov","mil","gok","gob","gkp","gop","gos","gog","ltd","web","fam","biz" ],

	"ru": [ "ac","com","edu","gov","int","mil","net","org","pp","adygeya","bashkiria","buryatia","ulan-ude","grozny",
		"cap","dagestan","nalchik","kalmykia","kchr","karelia","ptz","khakassia","komi","mari-el","mari","joshkar-ola",
		"mordovia","yakutia","vladikavkaz","kazan","tatarstan","tuva","izhevsk","udmurtia","udm","altai","kamchatka",
		"khabarovsk","khv","kuban","krasnoyarsk","perm","marine","vladivostok","stavropol","stv","chita","amur",
		"arkhangelsk","astrakhan","belgorod","bryansk","chelyabinsk","chel","ivanovo","irkutsk","koenig","kaluga",
		"kemerovo","kirov","vyatka","kostroma","kurgan","kursk","lipetsk","magadan","mosreg","murmansk","nnov","nov",
		"novosibirsk","nsk","omsk","orenburg","oryol","penza","pskov","rnd","ryazan","samara","saratov","sakhalin",
		"yuzhno-sakhalinsk","e-burg","yekaterinburg","smolensk","tambov","tver","tomsk","tom","tsk","tula","tyumen",
		"simbirsk","vladimir","volgograd","tsaritsyn","vologda","cbg","voronezh","vrn","yaroslavl","mos","msk","spb",
		"bir","jar","chukotka","surgut","yamal","amursk","baikal","cmw","fareast","jamal","kms","k-uralsk","kustanai",
		"kuzbass","magnitka","mytis","nakhodka","nkz","norilsk","snz","oskol","pyatigorsk","rubtsovsk","syzran",
		"tlt","vdonsk" ],

	"th": [ "ac","co","go","mi","or","net","in" ],

	"tr": [ "gov","mil","tsk","k12","edu","av","dr","bel","pol","kep","com","net","org","info","bbs","nom","tv",
		"biz","tel","gen","web","name" ],

	"tt": [ "co","com","org","net","travel","museum","aero","tel","name","charity","mil","edu","gov" ],

	"ua": [ "com","edu","gov","net","in","org","cherkasy","chernigov","chernivtsi","crimea","dnipropetrovsk",
		"donetsk","ivano-frankivsk","kharkiv","kherson","khmelnitskiy","kirovograd","kyiv","lugansk","lutsk",
		"lviv","nikolaev","odesa","poltava","rivne","sevastopol","sumy","ternopil","uzhgorod","vinnica","yalta",
		"zaporizhzhe","zhitomir" ],
		
	"uk": [ "ac","bl","co","gov","judiciary","ltd","me","mod","net","nhs","nic","org","parliament","plc","police",
		"rct","royal","sch","ukaea" ],

	"us": [ "fed","isa","nsn","dni" ],

	"zm": [ "ac","biz","co","com","edu","gov","info","mil","net","org","sch" ],

	"za": [ "ac","co","edu","gov","law","mil","net","nom","org","web","alt","ngo","tm","agric","grondar","nis" ]

}

export const zaSchools = [ "ecape", "fs", "gp", "kzn", "mpm", "ncape", "lp", "nw", "wcape" ]

export const regionalTlds = {
  "africa": {
  	"tld": "africa", "code": "af",
  	"countries": [
	    "dz", "ao", "sh", "bj", "bw", "bf", "bi", "cm", "cv", "cf", "td", "km", "cg", "cd", "dj", "eg", "gq", 
	    "er", "sz", "et", "ga", "gm", "gh", "gn", "gw", "ci", "ke", "ls", "lr", "ly", "mg", "mw", "ml", "mr", 
	    "mu", "yt", "ma", "mz", "na", "ne", "ng", "st", "re", "rw", "st", "sn", "sc", "sl", "so", "za", "ss", 
	    "sh", "sd", "sz", "tz", "tg", "tn", "ug", "cd", "zm", "tz", "zw"]
  },
  "europe": {
  	"tld": "eu", "code": "eu",
  	"countries": [
		"al" "ad" "at" "by" "be" "ba" "bg" "hr" "cy" "cz" "dk" "ee" "fo" "fi" "fr" "de" "gi" "gr" "hu" "is",
		"ie" "im" "it" "rs" "lv" "li" "lt" "lu" "mk" "mt" "md" "mc" "me" "nl" "no" "pl" "pt" "ro" "ru" "sm",
		"rs" "sk" "si" "es" "se" "ch" "ua" "gb" "va" "rs"]
  }
}